version: '3'

services:
  ml-model:
    build: .
    volumes:
      - .:/app
    ports:
      - "8888:8888"
      - "8082:5000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "8083:5000"
    volumes:
      - ./mlruns:/mlruns
    command: mlflow server --host 0.0.0.0 --port 5000
